[tool.poetry]
name = "kaggle-projects"
version = "1.0.0"
description = "Kaggle projects repo"
authors = ["Jason Wedderburn <jasonwj96@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.0"
torch = "^2.5.1"